### ISSUE TITLE
Is it possible to catch and log an error in the fetch method?

### ISSUE THREAD

**Issue by mhinton** [gaelreyrol/nuxt-rollbar-module#1]
Here is an example of what I am trying to do:

```js
async fetch({ app, route, store }) {
  try {
    // get data
    throw new Error("test error handling");
  } catch (e) {
      if (process.client) {
        this.rollbar.error(e); // this works fine
      } else {
        Vue.rollbar.error(e); // no rollbar property on Vue
        app.rollbar.debug(e); // no rollbar property on app
      }    
  }
}
```

**Comment by Zevran** [comment]
Hi @mhinton, could you provide a context to this example ?

**Comment by Kasheftin** [comment]
As I understand, nuxt-rollbar-module uses vue-rollbar on the client side. That's why we have this.rollbar, Vue.rollbar, this.$rollbar in the vue components. It works on the client side perfectly. 

Then, assume we make a number of requests in nuxtClientInit action and then in fetch or asyncData methods of the page. And we want to push errors to rollbar in these functions using serverAccessToken. How to do that? I see there's nuxt.hook for render:errorMiddleware that uses this token. But what about the other places on server side?

**Comment by Zevran** [comment]
Well I am sure it is possible to use it on other hooks, when I did it I inspired from [sentry-module](https://github.com/nuxt-community/sentry-module).
So maybe you can try to implement the other hooks the same way as sentry's module and make a pull request ?
I don't have enough time to do it myself actually.
